### ISSUE TITLE
Fix critical drone simulation bug - erroneous journey waypoints

### ISSUE THREAD

**Issue by samuknet** [ICdrones11/TestingEngine#12]
If you run `python engine.py`, the output will be written to `output/output.json`.  Here, every other waypoint has an incorrect `latitude` value of `38....`.  

This is a bug which needs to be fixed - the waypoints for the test journey from SK to Hammersmith should not jump around like this.

Note: This might just be a bug in the [logger](https://github.com/ICdrones11/TestingEngine/blob/master/droneLogger.py) but could be a wider issues.

**Comment by samuknet** [comment]
@dc3315  This is the biggest issue currently blocking us.

This is the data the logger spits out when doing the test journey from SK to Hammersmith:
`[{"uid": "d1", "waypoints": [{"lat": 51.49415, "timestamp": 0, "alt": 1500, "lon": -0.174685}, {"lat": 38.50614691406968, "timestamp": 1, "alt": 1499.8706578919664, "lon": -0.17958523499281276}, {"lat": 51.49414237568699, "timestamp": 2, "alt": 1507.1920957332477, "lon": -0.18574437579895126}, {"lat": 38.50615407721468, "timestamp": 3, "alt": 1507.1271794522181, "lon": -0.19064465146995363}, {"lat": 51.49413463299523, "timestamp": 4, "alt": 1514.4998678136617, "lon": -0.19680384159477476}, {"lat": 38.50616135872591, "timestamp": 5, "alt": 1514.4993785386905, "lon": -0.201704157680782}, {"lat": 51.49412677192351, "timestamp": 6, "alt": 1521.9233182631433, "lon": -0.2078633967673364}, {"lat": 38.50616875860465, "timestamp": 7, "alt": 1521.9872571667656, "lon": -0.21276375300515227}, {"lat": 51.49411879247067, "timestamp": 8, "alt": 1529.4624490914866, "lon": -0.21892304069647578}, {"lat": 38.50617627685213, "timestamp": 9, "alt": 1529.5908173378557, "lon": -0.2238234368228929}, {"lat": 51.49411069463553, "timestamp": 10, "alt": 1537.1172622963786, "lon": -0.22998277276200682}]}]`

The latitudes flip between correct values and erroneous "38..." values.

**Comment by dc3315** [comment]
fixed! The output now makes a lot more sens:

`[{"uid": "d1", "waypoints": [{"lat": 51.49415, "timestamp": 0, "alt": 1500, "lon": -0.174685}, {"lat": 51.49385308593032, "timestamp": 1, "alt": 1499.8706578919664, "lon": -0.17958523499281276}, {"lat": 51.49355637603793, "timestamp": 2, "alt": 1499.7700309120119, "lon": -0.18448551055567083}, {"lat": 51.493259870329375, "timestamp": 3, "alt": 1499.6981190601364, "lon": -0.18938582661738929}, {"lat": 51.4929635688112, "timestamp": 4, "alt": 1499.654922339134, "lon": -0.19428618310677945}, {"lat": 51.492667471489916, "timestamp": 5, "alt": 1499.6404407480732, "lon": -0.19918657995264924}, {"lat": 51.49237157837205, "timestamp": 6, "alt": 1499.6546742878854, "lon": -0.20408701708380306}, {"lat": 51.49207588946411, "timestamp": 7, "alt": 1499.697622959502, "lon": -0.20898749442904174}, {"lat": 51.491780404772584, "timestamp": 8, "alt": 1499.7692867610604, "lon": -0.21388801191716258}, {"lat": 51.49148512430396, "timestamp": 9, "alt": 1499.8696656925604, "lon": -0.21878856947695938}, {"lat": 51.49119004806472, "timestamp": 10, "alt": 1499.9987597512081, "lon": -0.22368916703722233}]}]`
