### ISSUE TITLE
Create new type for polar coordinates

### ISSUE THREAD

**Issue by samuknet** [ICdrones11/TestingEngine#14]
We should continue using the existing `Vector(x, y, z)` class for velocities however for polar coordinate positions we should use a new class for these say, `Polar(lat, lon, alt)`.

This reduces the chance of errors in mixing up latitude, longitude and altitude and cartesian coordinates as they would have to be explicitly requested like: `polarCoord["latititude"]` for example. It also reduces the chance of an error where we accidentally use a `latitude` value as `longitude` and vice versa.

**Comment by dc3315** [comment]
closed.
