### ISSUE TITLE
Make Cesium endTime match the point where the simulation ends

### ISSUE THREAD

**Issue by samuknet** [ICdrones11/TestingEngine#17]
At the moment, the simulation only takes up a small portion of the Cesium timeline and Cesium keeps simulating after this point.

We should change the line [here](https://github.com/ICdrones11/TestingEngine/blob/master/visualiser/js/main.js#L50) so that the stop time is calculated to be the last timestamp given in the input data.

**Comment by AdkaJ** [comment]
fca417376bda0849262ef11752f2851b48d39314
